export const reducerCases = {
    SET_TOKEN:"SET_TOKEN",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_PLAYING:"SET_PALYING",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
    SET_PLATLIST_ID:" SET_PLATLIST_ID"
}